config/routes.rb
Rails.application.routes.draw do
	root to: 'articles#index'
  resources :articles do
  	resources :comments
  end	

  resources :tags
  resources :authors

  resources :author_sessions, only: [:new, :create, :destroy]

  resources :popular_articles, only: [:index]

  resources :articles_by_month, only: [:index]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings

	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", 	"image/jpeg", "image/png"]

	def tag_list
		tags.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect {|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect{ |name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end

	def increment_views
		self.views = self.views + 1
		self.save
	end

	def creation_month
		self.created_at.strftime('%B')
	end

end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Password should match confirmation", if: :password 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates_presence_of :author_name, :body

  has_many :articles, through: :taggings
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
	def to_s
		name
	end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	include ArticlesHelper

	before_filter :require_login, except: [:index, :show]

	def index
		@articles = Article.all

		respond_to do |format|
			format.html
			format.rss {render :layout => false}
		end
	end

	def show
		@article = Article.find(params[:id])
		@article.increment_views
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.save

		flash.notice = "Article '#{@article.title}' Created!"

		redirect_to article_path(@article)
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "Article '#{@article.title}' Updated!"

		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		flash.notice = "Article '#{@article.title}' Deleted!"

		redirect_to articles_path
	end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	# renders the related form
	def new

	end

	# accepts the submission of the form
	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
		else
			flash.now.alert = 'Login failed'
			render action: :new
		end
	end

	# removes an author record
	def destroy
		logout
		redirect_to(:authors, notice: 'Logged out!')
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    def zero_authors_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	include CommentsHelper

	before_filter :require_login, except: [:create]

	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]

		@comment.save

		redirect_to article_path(@comment.article)
	end

end

app/controllers/popular_articles_controller.rb
class PopularArticlesController < ApplicationController

	def index
		@articles = Article.all.sort_by{|article| article.views}.reverse[0..2]
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	before_filter :require_login, only: [:destroy]

	def index
		@tags = Tag.all
	end

	def show
		@tag = Tag.find(params[:id])
	end

	def destroy 
		@tag = Tag.find(params[:id])
		@tag.destroy

		flash.notice = "Article #{@tag.name} Deleted!"

		redirect_to tags_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_by_month_helper.rb
module ArticlesByMonthHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

app/helpers/popular_articles_helper.rb
module PopularArticlesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Blogger</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= auto_discovery_link_tag :rss, articles_url(:format => :rss) %>
	</head>
	<body>

		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <%= link_to "Blogger App", articles_path, class: 'navbar-brand' %>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse pull-left" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li><%= link_to "Write an Article", new_article_path %></li>
		        <li><%= link_to "Popular Articles", popular_articles_path %></li>
		        <li><%= link_to "Articles by Month", articles_by_month_index_path %></li>
		        <li><%= link_to "RSS Feed", articles_url(:format => :rss) %></li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav><!-- navbar end -->

		<p class="flash"><%= flash.notice %></p>
		<div id="container container-fluid">
			<div id="content">
				<%= yield %>
				<hr>
				<h6>
				<% if logged_in? %>
					<%= "Logged in as #{current_user.email}" %>
					<%= link_to "(logout)", logout_path %>
				<% else %>
					<%= link_to "(login)", login_path %>
				<% end %>
				</h6>
			</div>
		</div>
	</body>
</html>

app/views/shared/_article_index.html.erb
<ul id="articles">
	<% @articles.each do |article| %>
		<li>
			<%= link_to article.title, article_path(article) %>
		</li>
	<% end %>
</ul>